apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: k8s-cicd-dev

namePrefix: dev-

resources:
  - ../../base

patches:
  - path: deployment-patch.yaml
  - path: hpa-patch.yaml

configMapGenerator:
  - name: k8s-cicd-api-config
    behavior: merge
    literals:
      - LOG_LEVEL=debug
      - LOG_FORMAT=simple
      - RATE_LIMIT_MAX=1000

images:
  - name: k8s-cicd-api
    newName: k8s-cicd-api
    newTag: latest
