apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: k8s-cicd-dev

namePrefix: dev-

resources:
- ../../base

patches:
- path: deployment-patch.yaml
- path: hpa-patch.yaml

configMapGenerator:
- behavior: merge
  literals:
  - LOG_LEVEL=debug
  - LOG_FORMAT=simple
  - RATE_LIMIT_MAX=1000
  name: k8s-cicd-api-config

images:
- name: k8s-cicd-api
  newName: ghcr.io/hitesh0106/k8s-cluster-gitops-config
  newTag: v1.0.0-eca56eb
