apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: k8s-cicd-staging

namePrefix: staging-

resources:
- ../../base


patches:
- path: deployment-patch.yaml
- path: hpa-patch.yaml
- patch: |-
    apiVersion: v1
    kind: ConfigMap
    metadata:
      name: k8s-cicd-api-config
    data:
      LOG_LEVEL: "info"
      LOG_FORMAT: "json"

images:
- name: k8s-cicd-api
  newName: ghcr.io/hitesh0106/k8s-cluster-gitops-config
  newTag: v1.0.0-6f9c06a
